# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
            - name: run .travis.yml

            - name: TravBot-Testing-Actions
  # You may pin to the exact commit or the version.
  # uses: keanuplayz/TravBotGH@d1ded9e5517ab30f30410c27a0e243dde8c4e66a
  uses: keanuplayz/TravBotGH@1.0.1
          
 
  # You may pin to the exact commit or the version.
  # uses: ktomk/run-travis-yml@496c4e756b55e38069011a628c89b2301556d999
  uses: ktomk/run-travis-yml@v1.8.1
  with:
    # Path to `.travis.yml` file. Leave empty / unset for default
`.travis.yml`. Relative to project root. Overrides the
`TRAVIS_YAML_FILE` environment variable if non-empty.

    file: # optional, default is 
    # Space separated list of steps to run. Leave empty
/ unset to run all custom steps.

    steps: # default is 
    # Deprecated: Space separated list of steps to run
(originally misnamed stages). Leave empty / unset to run
all custom steps. Use `inputs.steps` instead. Note:
`input.stages` might be re-used for different or just error
in a future version; change early.

    stages: # default is 
    # Allow the .travis.yml build to fail. Possible values are
`true` and `false`. Overrides the `TRAVIS_ALLOW_FAILURE`
environment variable if set.

    allow-failure: # optional, default is 
    # alias of `allow-failure`
    allow_failure: # optional, default is 
    # Name of the run-job. Possible values are the ones the
plan is listing. By default, the original root step-scripts
are in use. If a job has a name, it can be used as well.

    run-job: # optional, default is 
    # alias of `run-job`
    run_job: # optional, default is 
    # Dry-run the run-job. Possible values are `true` and
`false`.

    dry-run-job: # optional, default is 
    # alias of `dry-run-job`
    dry_run_job: # optional, default is 

                      - name: TravBot-Testing-Actions
  # You may pin to the exact commit or the version.
  # uses: keanuplayz/TravBotGH@d1ded9e5517ab30f30410c27a0e243dde8c4e66a
  uses: keanuplayz/TravBotGH@1.0.1
          
